namespace UKMCAB.Web.UI;

public static class Constants
{
    public const string MainLayoutPath = "~/Views/Shared/_Layout.cshtml";
    public const string SiteName = "UKMCAB alpha - GOV.UK";
    public const string NotProvided = "Not provided";

    public const int SearchResultPerPage = 20;
    public const string LastUpdatedSortValue = "lastupd";
    public const string A2ZSortValue = "a2z";
    public const string Z2ASortValue = "z2a";

    public static class Config
    {
        public const string ContainerNameDataProtectionKeys = "dataprotectionkeys";
    }

    public class Roles
    {
        public const string OPSSAdmin = nameof(OPSSAdmin);
        public const string UKASUser = nameof(UKASUser);
        public const string OGDUser = nameof(OGDUser);

        public static readonly List<string> AuthRoles = new List<string>
        {
            nameof(OPSSAdmin),
            nameof(UKASUser),
            nameof(OGDUser),
        };
    }

    public class ErrorMessages
    {
        public const string InvalidLoginAttempt = "The information provided is not right, try again";
    }

    public static class Lists
    {
        public static readonly List<string> LegislativeAreas = new()
        {
            "Cableway Installation",
            "Construction Products",
            "Ecodesign",
            "Electromagnetic Compatibility",
            "Equipment and protective systems for use in potentially explosive atmospheres",
            "Explosives",
            "Gas appliances and related",
            "Lifts",
            "Machinery",
            "Marine equipment",
            "Measuring instruments",
            "Medical devices",
            "Noise emissions in the environment by equipment for use outdoors",
            "Non-automatic weighing instruments",
            "Personal protective equipment",
            "Pressure equipment",
            "Pyrotechnics",
            "Radio equipment",
            "Railway interoperability",
            "Recreational craft",
            "Simple pressure vessels",
            "Toys",
            "Transportable pressure equipment"
        };

        public static readonly List<string> Countries = new()
        {
            "United Kingdom",
            "Afghanistan",
            "Albania",
            "Algeria",
            "Andorra",
            "Angola",
            "Antigua and Barbuda",
            "Argentina",
            "Armenia",
            "Australia",
            "Austria",
            "Azerbaijan",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Belarus",
            "Belgium",
            "Belize",
            "Benin",
            "Bhutan",
            "Bolivia",
            "Bosnia and Herzegovina",
            "Botswana",
            "Brazil",
            "Brunei",
            "Bulgaria",
            "Burkina Faso",
            "Burma",
            "Burundi",
            "Cambodia",
            "Cameroon",
            "Canada",
            "Cape Verde",
            "Central African Republic",
            "Chad",
            "Chile",
            "China",
            "Colombia",
            "Comoros",
            "Congo",
            "Congo (Democratic Republic)",
            "Costa Rica",
            "Croatia",
            "Cuba",
            "Cyprus",
            "Czechia",
            "Denmark",
            "Djibouti",
            "Dominica",
            "Dominican Republic",
            "East Timor",
            "Ecuador",
            "Egypt",
            "El Salvador",
            "Equatorial Guinea",
            "Eritrea",
            "Estonia",
            "Eswatini",
            "Ethiopia",
            "Fiji",
            "Finland",
            "France",
            "Gabon",
            "Georgia",
            "Germany",
            "Ghana",
            "Greece",
            "Grenada",
            "Guatemala",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Honduras",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Iran",
            "Iraq",
            "Ireland",
            "Israel",
            "Italy",
            "Ivory Coast",
            "Jamaica",
            "Japan",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Kiribati",
            "North Korea",
            "South Korea",
            "Kosovo",
            "Kuwait",
            "Kyrgyzstan",
            "Laos",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Liberia",
            "Libya",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Marshall Islands",
            "Mauritania",
            "Mauritius",
            "Mexico",
            "Micronesia",
            "Moldova",
            "Monaco",
            "Mongolia",
            "Montenegro",
            "Morocco",
            "Mozambique",
            "Namibia",
            "Nauru",
            "Nepal",
            "Netherlands",
            "New Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "North Macedonia",
            "Norway",
            "Oman",
            "Pakistan",
            "Palau",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Poland",
            "Portugal",
            "Qatar",
            "Romania",
            "Russia",
            "Rwanda",
            "St Kitts and Nevis",
            "St Lucia",
            "St Vincent",
            "Samoa",
            "San Marino",
            "Sao Tome and Principe",
            "Saudi Arabia",
            "Senegal",
            "Serbia",
            "Seychelles",
            "Sierra Leone",
            "Singapore",
            "Slovakia",
            "Slovenia",
            "Solomon Islands",
            "Somalia",
            "South Africa",
            "South Sudan",
            "Spain",
            "Sri Lanka",
            "Sudan",
            "Suriname",
            "Sweden",
            "Switzerland",
            "Syria",
            "Tajikistan",
            "Tanzania",
            "Thailand",
            "The Bahamas",
            "The Gambia",
            "Togo",
            "Tonga",
            "Trinidad and Tobago",
            "Tunisia",
            "Turkey",
            "Turkmenistan",
            "Tuvalu",
            "Uganda",
            "Ukraine",
            "United Arab Emirates",
            "United States",
            "Uruguay",
            "Uzbekistan",
            "Vanuatu",
            "Vatican City",
            "Venezuela",
            "Vietnam",
            "Yemen",
            "Zambia",
            "Zimbabwe"
        };

        public static readonly List<string> BodyTypes = new()
        {
            "Approved body",
            "Technical assessment body",
            "User inspectorate",
            "Recognised third-party",
            "Overseas Body",
            "NI Notified body",
            "UK body designated under MRA: Australia",
            "UK body designated under MRA: New Zealand",
            "UK body designated under MRA: USA",
            "UK body designated under MRA: Japan",
            "UK body designated under MRA: Canada"
        };
    }
}

