namespace UKMCAB.Web.UI.Models.ViewModels.Admin.Notification;

public record NotificationsViewModel(string PageTitle, NotificationsViewModelTab UnassignedTab,NotificationsViewModelTab AssignedToMeTab,NotificationsViewModelTab AssignedToGroupTab,NotificationsViewModelTab CompletedTab) : BasicPageModel(PageTitle);