services:
   ukmcab-web:
     image: ${DOCKER_REGISTRY-}ukmcab
     hostname: ukmcabweb
     container_name: ukmcabweb
     ports: 
      - 7060:8080
     build:
       context: .
       dockerfile: UKMCAB.Web.UI/Dockerfile
     healthcheck:
       test: curl --fail http://localhost:9080/health-check || exit 1
       interval: 40s
       timeout: 30s
       retries: 3
       start_period: 60s
     depends_on:
       ukmcab-db:
         condition: service_healthy
       ukmcab-cache:
         condition: service_healthy
     networks:
       - app-network
   ukmcab-db:
     image: postgres:latest
     hostname: ukmcabdb
     container_name: ukmcabdb
     environment:
      - POSTGRES_DB=ukmcab
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
     volumes: 
      - ./.containers/audit-db:/var/lib/postgresql/data
     ports:
      - 5435:5432
     healthcheck:
       test: ["CMD-SHELL", "pg_isready -U postgres -d ukmcab || exit 1"]
       interval: 10s
       timeout: 5s
       retries: 5
     networks:
       - app-network
   ukmcab-cache:
     image: redis:latest
     hostname: ukmcabcache
     container_name: ukmcabcache
     restart: always
     ports:
       - "127.0.0.1:6380:6379"
     command: redis-server --save 20 1 --loglevel verbose --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
     volumes: 
      - ./.containers/redis-cache:/data
     healthcheck:
       test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
     networks:
       - app-network
   ukmcab-localstack:
     hostname: "ukmcablocalstack"
     container_name: "ukmcablocalstack"
     image: localstack/localstack
     ports:
       - 4566:4566            # LocalStack Gateway
       - 4510-4559:4510-4559  # external services port range
     environment:
       - SERVICES=s3
       - DEBUG=1
       - DATA_DIR=/data
     volumes:
       - ./.containers/localstack:/data
       - /var/run/docker.sock:/var/run/docker.sock
     networks:
       - app-network
networks:
  app-network:
