services:
   ukmcab-web:
     image: ${DOCKER_REGISTRY-}ukmcab
     hostname: ukmcabweb
     container_name: ukmcabweb
     ports: 
      - 7060:8080
     build:
       context: .
       dockerfile: UKMCAB.Web.UI/Dockerfile
     depends_on:
       ukmcab-db:
         condition: service_healthy
       ukmcab-cache:
         condition: service_healthy
     networks:
       - app-network
     environment:
        - TZ=Europe/London
   ukmcab-db:
     image: postgres:latest
     hostname: ukmcabdb
     container_name: ukmcabdb
     environment:
      - POSTGRES_DB=ukmcab
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Europe/London
     volumes: 
      - ./.containers/audit-db:/var/lib/postgresql/data
     ports:
      - 5435:5432
     healthcheck:
       test: ["CMD-SHELL", "pg_isready -U postgres -d ukmcab || exit 1"]
       interval: 10s
       timeout: 5s
       retries: 5
     networks:
       - app-network
   ukmcab-cache:
     image: redis:latest
     hostname: ukmcabcache
     container_name: ukmcabcache
     restart: always
     ports:
       - "127.0.0.1:6380:6379"
     command: redis-server --save 20 1 --loglevel verbose --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
     volumes: 
      - ./.containers/redis-cache:/data
     healthcheck:
       test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
     networks:
       - app-network
   ukmcab-localstack:
     hostname: "ukmcablocalstack"
     container_name: "ukmcablocalstack"
     image: localstack/localstack
     ports:
       - 4566:4566            # LocalStack Gateway
       - 4510-4559:4510-4559  # external services port range
     environment:
       - SERVICES=s3,opensearch
       - DEBUG=1
       - DATA_DIR=/data
       - OPENSEARCH_CUSTOM_BACKEND=http://ukmcabopensearch:9200
     volumes:
       - ./.containers/localstack:/data
       - /var/run/docker.sock:/var/run/docker.sock
     networks:
       - app-network
     depends_on:
       - ukmcab-opensearch
   ukmcab-opensearch:
     hostname: "ukmcabopensearch"
     container_name: "ukmcabopensearch"
     image: opensearchproject/opensearch
     environment:
         - node.name=opensearch
         - cluster.name=opensearch-docker-cluster
         - discovery.type=single-node
         - bootstrap.memory_lock=true
         - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
         - "DISABLE_SECURITY_PLUGIN=true"
     ports:
         - 9200:9200
     ulimits:
         memlock:
             soft: -1
             hard: -1
     volumes:
         - ./.containers/opensearch:/usr/share/opensearch/data
     healthcheck:
       test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
       interval: 30s
       timeout: 10s
       retries: 5
     networks:
         - app-network
networks:
  app-network:
