name: Azure IaC deploy (stage)

on: 
  push:
    paths:
      - 'bicep/**/*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        scope: 'subscription'
        region: 'uksouth'
        template: './bicep/main.bicep'
        parameters: ./bicep/stage.parameters.json basicAuthPassword=${{ secrets.BASIC_AUTH_PASSWORD_STAGE }}
        failOnStdErr: false
