name: Azure IaC deploy (dev) 

on: 
  push:
    branches:
     - dev
    paths:
      - 'bicep/**/*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        scope: 'subscription'
        region: 'uksouth'
        template: './bicep/main.bicep'
        parameters: ./bicep/dev.parameters.json basicAuthPassword=${{ secrets.BASIC_AUTH_PASSWORD_DEV }} sslCertPfxBase64=${{ secrets.SSL_CERT_DEV }} dataProtectionX509CertBase64=${{ secrets.DATA_PROTECTION_X509_CERT_DEV }}
        failOnStdErr: false
