name: App service deploy

on:
  # workflow_dispatch
  push:
   branches:
     - main
   paths:
     - 'src/**/*'

env:
  AZURE_WEBAPP_NAME: app-opss-ukmcab-dev
  AZURE_WEBAPP_PACKAGE_PATH: UKMCAB.Web.UI/publish
  DOTNET_VERSION: '6.0.x'
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  WORKING_DIRECTORY: src/UKMCAB.Web.UI
  TEST_PROJECT_DIR: src/UKMCAB.Test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@main
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}



      - name: Setup Node.js
        uses: actions/setup-node@v2
        working-directory: ${{ env.WORKING_DIRECTORY }}
        with:
          node-version: '16'

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        working-directory: ${{ env.WORKING_DIRECTORY }}
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install NPM dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm ci --ignore-scripts

      - name: Run Gulp task
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: gulp


      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Run dotnet build and publish
      - name: Restore
        run: dotnet restore "${{ env.WORKING_DIRECTORY }}"

      - name: Build
        run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
      
      - name: Test
        run: dotnet test "${{ env.TEST_PROJECT_DIR }}"
      
      - name: Publish
        run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
          
      # Deploy to Azure Web apps
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      
      - name: logout
        run: |
          az logout