name: dev-iac-deploy

on: 
  workflow_dispatch:
  push:
    branches:
     - dev
    paths:
      - 'bicep/**/*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        scope: 'subscription'
        region: 'uksouth'
        template: './bicep/main.bicep'
        parameters: ./bicep/dev.parameters.json 
          basicAuthPassword=${{ secrets.BASIC_AUTH_PASSWORD_DEV }} 
          sslCertPfxBase64=${{ secrets.SSL_CERT_DEV_2024 }} 
          dataProtectionX509CertBase64=${{ secrets.DATA_PROTECTION_X509_CERT_DEV }} 
          govukNotifyApiKey=${{ secrets.GOVUK_NOTIFY_API_KEY_DEV }}
          encryptionKey=${{ secrets.DEV_ENCRYPTION_KEY }}
          oneLoginClientId=${{ secrets.DEV_ONELOGINCLIENTID }}
          oneLoginKeyPairBase64=${{ secrets.DEV_ONELOGINKEYPAIRBASE64 }}
        failOnStdErr: false
