name: preprod-iac-deploy

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_UAT }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        scope: 'subscription'
        region: 'uksouth'
        template: './bicep/main.bicep'
        parameters: ./bicep/preprod.parameters.json 
          basicAuthPassword=${{ secrets.PP_BASIC_AUTH_PASSWORD }} 
          sslCertPfxBase64=${{ secrets.PP_SSL_CERT_24 }}
          dataProtectionX509CertBase64=${{ secrets.PP_DATA_PROTECTION_X509_CERT }} 
          govukNotifyApiKey=${{ secrets.PP_GOVUK_NOTIFY_API_KEY }}
          encryptionKey=${{ secrets.PP_ENCRYPTION_KEY }}
          oneLoginClientId=${{ secrets.PP_ONELOGINCLIENTID }}
          oneLoginKeyPairBase64=${{ secrets.PP_ONELOGINKEYPAIRBASE64 }}
        failOnStdErr: false
