name: preprod-iac-deploy

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_PROD }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        scope: 'subscription'
        region: 'uksouth'
        template: './bicep/main.bicep'
        parameters: ./bicep/prod.parameters.json 
          basicAuthPassword=${{ secrets.PROD_BASIC_AUTH_PASSWORD }} 
          sslCertPfxBase64=${{ secrets.PROD_SSL_CERT }} 
          dataProtectionX509CertBase64=${{ secrets.PROD_DATA_PROTECTION_X509_CERT }} 
          govukNotifyApiKey=${{ secrets.PROD_GOVUK_NOTIFY_API_KEY }} 
          sslCertPfxBase64VNextSlot=${{ secrets.PROD_SSL_CERT_VNEXT }}
        failOnStdErr: false
