name: stage-iac-deploy

on: 
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write

    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        scope: 'subscription'
        region: 'uksouth'
        template: './bicep/main.bicep'
        parameters: ./bicep/stage.parameters.json 
          basicAuthPassword=${{ secrets.BASIC_AUTH_PASSWORD_STAGE }} 
          sslCertPfxBase64=${{ secrets.SSL_CERT_STAGE_2025 }} 
          dataProtectionX509CertBase64=${{ secrets.DATA_PROTECTION_X509_CERT_STAGE }} 
          govukNotifyApiKey=${{ secrets.GOVUK_NOTIFY_API_KEY_STAGE }}
          encryptionKey=${{ secrets.STAGE_ENCRYPTION_KEY }}
          oneLoginClientId=${{ secrets.STAGE_ONELOGINCLIENTID }}
          oneLoginKeyPairBase64=${{ secrets.STAGE_ONELOGINKEYPAIRBASE64 }}
        failOnStdErr: false
